import { issue, type Issue } from "@backend-compiler/common";
import type { BackendIR } from "@backend-compiler/compiler";
import {
  emptyRenderResult,
  type RenderResult,
  type RenderedFile,
  type RootModuleImport,
  type TargetAdapter,
  type TargetRenderContext,
} from "@backend-compiler/target-sdk";
import { clientFiles } from "./client.js";
import { BASE_DEPENDENCIES, BASE_DEV_DEPENDENCIES, BASE_SCRIPTS } from "./deps.js";
import { MIGRATION_DIRECTORY, MIGRATIONS_ROOT, renderInitialMigration } from "./prisma-ddl.js";
import { renderDiffMigration } from "./prisma-ddl-diff.js";
import {
  buildSchemaSnapshot,
  parseSchemaSnapshot,
  serializeSchemaSnapshot,
} from "./schema-snapshot.js";
import { renderPrismaSchema } from "./prisma-schema.js";
import { projectFiles } from "./project.js";

export const TARGET_ID = "nestjs-prisma";
export const TARGET_VERSION = "0.2.0";

/** Model names Prisma or the generated code already uses. */
const RESERVED_ENTITY_NAMES = new Set(["Prisma", "PrismaClient", "App", "Health"]);

function sortedRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(record).sort(([left], [right]) => (left < right ? -1 : 1)));
}

function packageJson(context: TargetRenderContext, contributions: RenderResult): string {
  const manifest = {
    name: context.ir.project.name,
    version: "0.1.0",
    private: true,
    description: context.ir.project.description ?? "Generated by backendgen",
    license: "UNLICENSED",
    engines: { node: ">=22" },
    scripts: sortedRecord({ ...BASE_SCRIPTS, ...contributions.scripts }),
    dependencies: sortedRecord({ ...BASE_DEPENDENCIES, ...contributions.packageDependencies }),
    devDependencies: sortedRecord({
      ...BASE_DEV_DEPENDENCIES,
      ...contributions.packageDevDependencies,
    }),
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function appModule(contributions: RenderResult): string {
  const modules = contributions.rootModules.filter((entry) => entry.kind === "module");
  const guards = contributions.rootModules.filter((entry) => entry.kind === "global-guard");
  const providers = contributions.rootModules.filter((entry) => entry.kind === "provider");
  const filters = contributions.rootModules.filter((entry) => entry.kind === "global-filter");

  const featureImports = [...modules, ...guards, ...providers, ...filters]
    .map((entry: RootModuleImport) => `import { ${entry.symbol} } from '${entry.from}';`)
    .join("\n");

  const imports = [
    "ConfigModule.forRoot({ isGlobal: true, cache: true })",
    "EventEmitterModule.forRoot()",
    "PrismaModule",
    "HealthModule",
    ...modules.map((entry) => entry.symbol),
    // Imported last so that a custom provider overrides the generated default.
    "CustomModule",
  ];

  const providerEntries = [
    "{ provide: APP_FILTER, useClass: HttpExceptionFilter }",
    ...filters.map((entry) => `{ provide: APP_FILTER, useClass: ${entry.symbol} }`),
    ...guards.map((entry) => `{ provide: APP_GUARD, useClass: ${entry.symbol} }`),
    ...providers.map((entry) => entry.symbol),
  ];
  const coreProviders = ["APP_FILTER", ...(guards.length > 0 ? ["APP_GUARD"] : [])].join(", ");

  return `import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { ${coreProviders} } from '@nestjs/core';
import { EventEmitterModule } from '@nestjs/event-emitter';
import { CustomModule } from './custom/custom.module';
import { HttpExceptionFilter } from './generated/common/http-exception.filter';
import { HealthModule } from './generated/health/health.module';
import { PrismaModule } from './generated/prisma/prisma.module';
${featureImports}

@Module({
  imports: [
${imports.map((entry) => `    ${entry},`).join("\n")}
  ],
  providers: [
${providerEntries.map((entry) => `    ${entry},`).join("\n")}
  ],
})
export class AppModule {}
`;
}

function envExample(context: TargetRenderContext, contributions: RenderResult): string {
  const project = context.ir.project.name;
  const lines: string[] = [
    "# Copy to .env and replace every placeholder before starting the application.",
    "# The application refuses to boot when a required variable is missing.",
    "",
    "NODE_ENV=development",
    `PORT=${context.settings.port}`,
    "# Comma-separated exact browser origins. Leave empty to keep CORS disabled.",
    "CORS_ORIGINS=",
    "SWAGGER_ENABLED=false",
    "TRUST_PROXY_HOPS=0",
    "",
    "# PostgreSQL settings used by docker-compose.yml. Replace the password.",
    `POSTGRES_USER=${project}`,
    'POSTGRES_PASSWORD="replace-with-a-random-database-password"',
    `POSTGRES_DB=${project}`,
    "",
    "# PostgreSQL connection string for running the API directly on the host.",
    `DATABASE_URL="postgresql://${project}:replace-with-a-random-database-password@localhost:5432/${project}?schema=public"`,
  ];

  for (const entry of contributions.envExample) {
    lines.push("", `# ${entry.comment}`, `${entry.name}=${entry.value}`);
  }

  return `${lines.join("\n")}\n`;
}

function generated(path: string, contents: string): RenderedFile {
  return { path, contents, ownership: "generated" };
}

/**
 * Runs before anything reads configuration. Values are only applied when absent,
 * so an operator can still point a test run at a different provider, and the
 * `.env` file (loaded later, and which never overrides an existing variable)
 * cannot drag a test suite onto a real third-party service.
 */
function testEnvFile(contributions: RenderResult): string {
  const entries = Object.entries(contributions.testEnv).sort(([left], [right]) =>
    left < right ? -1 : 1,
  );

  return `/** Test defaults. Generated: an explicitly exported variable always wins. */
const TEST_DEFAULTS: Record<string, string> = {
${entries.map(([name, value]) => `  ${name}: '${value}',`).join("\n")}
};

for (const [name, value] of Object.entries(TEST_DEFAULTS)) {
  if (process.env[name] === undefined || process.env[name] === '') {
    process.env[name] = value;
  }
}
`;
}

export const nestjsPrismaTarget: TargetAdapter = {
  id: TARGET_ID,
  version: TARGET_VERSION,
  description:
    "NestJS 11 + Prisma 6 + PostgreSQL, REST/OpenAPI and typed client generation, immutable migrations, deterministic seeds, Jest tests, and Docker Compose.",
  supportedDatabases: ["postgresql"],
  capabilities: [
    "crud",
    "auth",
    "organizations",
    "reservations",
    "notifications",
    "jobs",
    "uploads",
    "webhooks",
    "soft-delete",
    "typed-client",
    "incremental-migrations",
    "deterministic-seeds",
  ],
  commands: {
    install: "npm install",
    build: "npm run build",
    test: "npm test",
    testIntegration: "npm run test:integration",
    format: "npx prettier --write .",
    migrate: "npm run db:deploy",
  },

  validate(ir: BackendIR): Issue[] {
    const issues: Issue[] = [];

    if (ir.target.database !== "postgresql") {
      issues.push(
        issue(
          "target.unsupported-database",
          "/target/database",
          `Target '${TARGET_ID}' supports postgresql only; got '${ir.target.database}'. The reservation overlap constraint depends on PostgreSQL exclusion constraints.`,
        ),
      );
    }

    for (const entity of ir.entities) {
      if (RESERVED_ENTITY_NAMES.has(entity.name)) {
        issues.push(
          issue(
            "target.reserved-entity-name",
            `/entities/${entity.name}`,
            `Entity name '${entity.name}' collides with a name reserved by the generated project`,
          ),
        );
      }

      for (const relation of entity.relations) {
        if (relation.type === "manyToMany") {
          issues.push(
            issue(
              "target.unsupported-relation",
              `/entities/${entity.name}/relations/${relation.name}`,
              "manyToMany relations are not supported by nestjs-prisma yet. Model the join table as an explicit entity with two belongsTo relations.",
            ),
          );
        }
      }
    }

    return issues;
  },

  renderProject(context: TargetRenderContext): RenderResult {
    return {
      ...emptyRenderResult(),
      files: [...projectFiles(context), ...clientFiles(context)],
      packageDependencies: { ...BASE_DEPENDENCIES },
      packageDevDependencies: { ...BASE_DEV_DEPENDENCIES },
      scripts: {
        ...BASE_SCRIPTS,
        ...(context.settings.client
          ? { "build:client": "tsc -p client/tsconfig.json" }
          : {}),
      },
    };
  },

  renderEntities(context: TargetRenderContext): RenderResult {
    return {
      ...emptyRenderResult(),
      files: [
        generated("prisma/schema.prisma", renderPrismaSchema(context.ir)),
        generated("prisma/migrations/migration_lock.toml", 'provider = "postgresql"\n'),
      ],
    };
  },

  migrations: {
    initialMigrationDirectory: MIGRATION_DIRECTORY,
    migrationsRoot: MIGRATIONS_ROOT,
    incrementalTag: "backendgen",
    buildSnapshot: buildSchemaSnapshot,
    serializeSnapshot: serializeSchemaSnapshot,
    parseSnapshot: parseSchemaSnapshot,
    renderDiffMigration,
  },

  compose(context: TargetRenderContext, contributions: RenderResult): RenderResult {
    return {
      ...emptyRenderResult(),
      files: [
        generated("package.json", packageJson(context, contributions)),
        generated("src/app.module.ts", appModule(contributions)),
        generated(".env.example", envExample(context, contributions)),
        generated("test/utils/test-env.ts", testEnvFile(contributions)),
        generated(
          `${MIGRATION_DIRECTORY}/migration.sql`,
          renderInitialMigration(context.ir, contributions.migrationSql),
        ),
      ],
    };
  },
};
