import type {
  BackendIR,
  NormalizedEntity,
  NormalizedField,
  NormalizedRelation,
} from "@backend-compiler/compiler";
import { databaseNames, enumFields, names, standaloneIndexes } from "./naming.js";

/** IR referential actions to Prisma's. Cascade only appears when a feature or the spec asked for it. */
const ON_DELETE_TO_PRISMA: Readonly<Record<NormalizedRelation["onDelete"], string>> = {
  restrict: "Restrict",
  cascade: "Cascade",
  setNull: "SetNull",
};

function prismaOnDelete(action: NormalizedRelation["onDelete"]): string {
  const rendered = ON_DELETE_TO_PRISMA[action];
  if (rendered === undefined) {
    throw new Error(`Unsupported or missing IR referential action: ${String(action)}`);
  }
  return rendered;
}

const SCALAR_TO_PRISMA: Readonly<Record<string, string>> = {
  string: "String",
  text: "String",
  integer: "Int",
  decimal: "Decimal",
  boolean: "Boolean",
  datetime: "DateTime",
  date: "DateTime",
  uuid: "String",
};

function prismaScalar(entity: NormalizedEntity, field: NormalizedField): string {
  if (field.enumValues) {
    return names.enumType(entity.name, field.name);
  }
  return SCALAR_TO_PRISMA[field.type] ?? "String";
}

function literal(value: string | number | boolean, isEnum: boolean): string {
  if (typeof value === "string") {
    return isEnum ? value : JSON.stringify(value);
  }
  return String(value);
}

function fieldLine(entity: NormalizedEntity, field: NormalizedField): string {
  const attributes: string[] = [];
  const type = `${prismaScalar(entity, field)}${field.required ? "" : "?"}`;

  if (field.type === "date") {
    attributes.push("@db.Date");
  }
  if (field.type === "datetime") {
    // Timezone-aware storage: PostgreSQL normalises to UTC on write instead of
    // silently trusting the session time zone.
    attributes.push("@db.Timestamptz(3)");
  }
  if (field.unique) {
    attributes.push(`@unique(map: "${databaseNames.index(entity.name, [field.name], true)}")`);
  }
  if (field.defaultValue !== null) {
    attributes.push(`@default(${literal(field.defaultValue, field.enumValues !== null)})`);
  }

  return `  ${field.name} ${type}${attributes.length > 0 ? ` ${attributes.join(" ")}` : ""}`;
}

function relationLines(entity: NormalizedEntity): string[] {
  const lines: string[] = [];

  for (const relation of entity.relations) {
    const model = names.model(relation.target);

    if (relation.owner && relation.foreignKey) {
      // to-one owning side: a scalar foreign key plus the relation field.
      const optional = relation.required ? "" : "?";
      const onDelete = prismaOnDelete(relation.onDelete);
      const foreignKeyName = databaseNames.foreignKey(entity.name, relation.foreignKey);
      lines.push(
        `  ${relation.foreignKey} String${optional}${
          relation.unique
            ? ` @unique(map: "${databaseNames.index(entity.name, [relation.foreignKey], true)}")`
            : ""
        }`,
      );
      lines.push(
        `  ${relation.name} ${model}${optional} @relation("${relation.relationName}", fields: [${relation.foreignKey}], references: [id], onDelete: ${onDelete}, map: "${foreignKeyName}")`,
      );
      continue;
    }

    if (relation.type === "hasMany" || relation.type === "manyToMany") {
      lines.push(`  ${relation.name} ${model}[] @relation("${relation.relationName}")`);
      continue;
    }

    // Non-owning to-one side (inverse of hasOne).
    lines.push(`  ${relation.name} ${model}? @relation("${relation.relationName}")`);
  }

  return lines;
}

function modelBlock(entity: NormalizedEntity): string {
  const lines: string[] = [
    `model ${names.model(entity.name)} {`,
    `  id String @id(map: "${databaseNames.primaryKey(entity.name)}") @default(uuid())`,
    "  createdAt DateTime @default(now()) @db.Timestamptz(3)",
    "  updatedAt DateTime @updatedAt @db.Timestamptz(3)",
  ];

  if (entity.softDelete) {
    lines.push("  deletedAt DateTime? @db.Timestamptz(3)");
  }

  for (const field of entity.fields) {
    lines.push(fieldLine(entity, field));
  }

  lines.push(...relationLines(entity));

  for (const index of standaloneIndexes(entity)) {
    const attribute = index.unique ? "@@unique" : "@@index";
    const map = databaseNames.index(entity.name, index.fields, index.unique);
    lines.push(`  ${attribute}([${index.fields.join(", ")}], map: "${map}")`);
  }

  lines.push("}");
  return lines.join("\n");
}

function enumBlocks(ir: BackendIR): string[] {
  return ir.entities.flatMap((entity) =>
    enumFields(entity).map(({ typeName, values }) =>
      [`enum ${typeName} {`, ...values.map((value) => `  ${value}`), "}"].join("\n"),
    ),
  );
}

/**
 * Renders `prisma/schema.prisma`. Column order is fixed (identity, timestamps,
 * soft delete, alphabetical fields, alphabetical relations) so that identical IR
 * always yields an identical file.
 */
export function renderPrismaSchema(ir: BackendIR): string {
  const header = [
    "// Generated by backendgen. Do not edit; run `backendgen generate` instead.",
    "",
    "generator client {",
    '  provider = "prisma-client-js"',
    "}",
    "",
    "datasource db {",
    `  provider = "${ir.target.database}"`,
    '  url      = env("DATABASE_URL")',
    "}",
  ].join("\n");

  const blocks = [header, ...enumBlocks(ir), ...ir.entities.map(modelBlock)];
  return `${blocks.join("\n\n")}\n`;
}
