import type {
  BackendIR,
  NormalizedEntity,
  NormalizedField,
  NormalizedRelation,
} from "@backend-compiler/compiler";
import { databaseNames, enumFields, foreignKeys, names, standaloneIndexes } from "./naming.js";

const SCALAR_TO_SQL: Readonly<Record<string, string>> = {
  string: "TEXT",
  text: "TEXT",
  integer: "INTEGER",
  decimal: "DECIMAL(65,30)",
  boolean: "BOOLEAN",
  datetime: "TIMESTAMPTZ(3)",
  date: "DATE",
  uuid: "TEXT",
};

const ON_DELETE_TO_SQL: Readonly<Record<NormalizedRelation["onDelete"], string>> = {
  restrict: "RESTRICT",
  cascade: "CASCADE",
  setNull: "SET NULL",
};

function sqlOnDelete(action: NormalizedRelation["onDelete"]): string {
  const rendered = ON_DELETE_TO_SQL[action];
  if (rendered === undefined) {
    throw new Error(`Unsupported or missing IR referential action: ${String(action)}`);
  }
  return rendered;
}

function sqlType(entity: NormalizedEntity, field: NormalizedField): string {
  if (field.enumValues) {
    return `"${names.enumType(entity.name, field.name)}"`;
  }
  return SCALAR_TO_SQL[field.type] ?? "TEXT";
}

function sqlDefault(field: NormalizedField): string {
  const value = field.defaultValue;
  if (value === null) return "";
  if (typeof value === "string") return ` DEFAULT '${value.replace(/'/g, "''")}'`;
  return ` DEFAULT ${String(value)}`;
}

function columnLines(entity: NormalizedEntity): string[] {
  const columns: string[] = [
    '    "id" TEXT NOT NULL',
    '    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP',
    '    "updatedAt" TIMESTAMPTZ(3) NOT NULL',
  ];

  if (entity.softDelete) {
    columns.push('    "deletedAt" TIMESTAMPTZ(3)');
  }

  for (const field of entity.fields) {
    const nullability = field.required ? " NOT NULL" : "";
    columns.push(
      `    "${field.name}" ${sqlType(entity, field)}${nullability}${sqlDefault(field)}`,
    );
  }

  for (const key of foreignKeys(entity)) {
    columns.push(`    "${key.name}" TEXT${key.required ? " NOT NULL" : ""}`);
  }

  columns.push(
    `    CONSTRAINT "${databaseNames.primaryKey(entity.name)}" PRIMARY KEY ("id")`,
  );
  return columns;
}

function createTable(entity: NormalizedEntity): string {
  return [
    "-- CreateTable",
    `CREATE TABLE "${entity.name}" (`,
    columnLines(entity).join(",\n"),
    ");",
  ].join("\n");
}

function createIndexes(entity: NormalizedEntity): string[] {
  const statements: string[] = [];

  for (const field of entity.fields) {
    if (field.unique) {
      statements.push(
        `CREATE UNIQUE INDEX "${databaseNames.index(entity.name, [field.name], true)}" ON "${entity.name}"("${field.name}");`,
      );
    }
  }

  for (const key of foreignKeys(entity)) {
    if (key.unique) {
      statements.push(
        `CREATE UNIQUE INDEX "${databaseNames.index(entity.name, [key.name], true)}" ON "${entity.name}"("${key.name}");`,
      );
    }
  }

  for (const index of standaloneIndexes(entity)) {
    const columns = index.fields.map((field) => `"${field}"`).join(", ");
    const name = databaseNames.index(entity.name, index.fields, index.unique);
    statements.push(
      `CREATE${index.unique ? " UNIQUE" : ""} INDEX "${name}" ON "${entity.name}"(${columns});`,
    );
  }

  return statements;
}

function foreignKeyStatements(entity: NormalizedEntity): string[] {
  return entity.relations
    .filter((relation) => relation.owner && relation.foreignKey !== null)
    .map((relation) => {
      const onDelete = sqlOnDelete(relation.onDelete);
      return (
        `ALTER TABLE "${entity.name}" ADD CONSTRAINT "${databaseNames.foreignKey(entity.name, relation.foreignKey!)}" ` +
        `FOREIGN KEY ("${relation.foreignKey}") REFERENCES "${relation.target}"("id") ` +
        `ON DELETE ${onDelete} ON UPDATE CASCADE;`
      );
    });
}

function createEnums(ir: BackendIR): string[] {
  return ir.entities.flatMap((entity) =>
    enumFields(entity).map(({ typeName, values }) => {
      const literals = values.map((value) => `'${value}'`).join(", ");
      return `CREATE TYPE "${typeName}" AS ENUM (${literals});`;
    }),
  );
}

/**
 * Emits the initial migration as SQL rather than shelling out to
 * `prisma migrate dev`, which needs a live shadow database. The result is
 * deterministic and applies offline with `prisma migrate deploy`.
 *
 * `extraSql` carries statements features cannot express through the Prisma
 * schema — most importantly the reservation overlap `EXCLUDE` constraint.
 */
export function renderInitialMigration(ir: BackendIR, extraSql: readonly string[]): string {
  const sections: string[] = [
    "-- Generated by backendgen. Applied with `prisma migrate deploy`.",
  ];

  const enums = createEnums(ir);
  if (enums.length > 0) {
    sections.push(["-- CreateEnum", ...enums].join("\n"));
  }

  for (const entity of ir.entities) {
    sections.push(createTable(entity));
  }

  const indexes = ir.entities.flatMap(createIndexes);
  if (indexes.length > 0) {
    sections.push(["-- CreateIndex", ...indexes].join("\n"));
  }

  const constraints = ir.entities.flatMap(foreignKeyStatements);
  if (constraints.length > 0) {
    sections.push(["-- AddForeignKey", ...constraints].join("\n"));
  }

  for (const statement of extraSql) {
    sections.push(statement.trim());
  }

  return `${sections.join("\n\n")}\n`;
}

export const MIGRATION_DIRECTORY = "prisma/migrations/00000000000000_init";
