import type { SchemaChange, SnapshotColumn } from "@backend-compiler/target-sdk";
import { renderCreateTable } from "./prisma-ddl.js";

const HEADER = "-- Generated by backendgen. Incremental migration. Applied with `prisma migrate deploy`.";

function columnClause(column: SnapshotColumn): string {
  const nullability = column.nullable ? "" : " NOT NULL";
  const fallback = column.default === null ? "" : ` DEFAULT ${column.default}`;
  return `"${column.name}" ${column.sqlType}${nullability}${fallback}`;
}

function commentBlock(prefix: string, sql: string): string {
  return sql
    .split("\n")
    .map((line) => `-- ${prefix}${line}`)
    .join("\n");
}

/**
 * Maps one change to its SQL block. Destructive statements are preceded by a
 * `-- DESTRUCTIVE:` line; the caller has already confirmed `allowDestructive`
 * before any destructive change reaches this function.
 */
function statementFor(change: SchemaChange): string {
  switch (change.kind) {
    case "create-table":
      return `-- CreateTable\n${renderCreateTable(change.table, change.snapshot.columns)}`;

    case "drop-table":
      return `-- DESTRUCTIVE: drops table "${change.table}" and every row in it.\nDROP TABLE "${change.table}";`;

    case "add-column":
      return `-- AddColumn\nALTER TABLE "${change.table}" ADD COLUMN ${columnClause(change.column)};`;

    case "drop-column":
      return (
        `-- DESTRUCTIVE: drops column "${change.table}"."${change.column}" and its data.\n` +
        `ALTER TABLE "${change.table}" DROP COLUMN "${change.column}";`
      );

    case "alter-column-type":
      return (
        `-- DESTRUCTIVE: changes the type of "${change.table}"."${change.column}" ` +
        `from ${change.from} to ${change.to}; existing values are cast in place.\n` +
        `ALTER TABLE "${change.table}" ALTER COLUMN "${change.column}" TYPE ${change.to} ` +
        `USING "${change.column}"::${change.to};`
      );

    case "alter-column-nullability":
      return (
        `ALTER TABLE "${change.table}" ALTER COLUMN "${change.column}" ` +
        `${change.nullable ? "DROP NOT NULL" : "SET NOT NULL"};`
      );

    case "alter-column-default":
      return (
        `ALTER TABLE "${change.table}" ALTER COLUMN "${change.column}" ` +
        `${change.default === null ? "DROP DEFAULT" : `SET DEFAULT ${change.default}`};`
      );

    case "add-index": {
      const columns = change.index.columns.map((column) => `"${column}"`).join(", ");
      return (
        `-- CreateIndex\nCREATE${change.index.unique ? " UNIQUE" : ""} INDEX "${change.index.name}" ` +
        `ON "${change.table}"(${columns});`
      );
    }

    case "drop-index":
      return `DROP INDEX "${change.index}";`;

    case "add-foreign-key": {
      const key = change.foreignKey;
      const destructive =
        change.recreated && key.onDelete === "CASCADE"
          ? `-- DESTRUCTIVE: recreates foreign key "${key.name}" with ON DELETE CASCADE; ` +
            "deleting a parent row will now delete its children.\n"
          : "-- AddForeignKey\n";
      return (
        `${destructive}ALTER TABLE "${change.table}" ADD CONSTRAINT "${key.name}" ` +
        `FOREIGN KEY ("${key.column}") REFERENCES "${key.target}"("id") ` +
        `ON DELETE ${key.onDelete} ON UPDATE CASCADE;`
      );
    }

    case "drop-foreign-key":
      return `ALTER TABLE "${change.table}" DROP CONSTRAINT "${change.foreignKey}";`;

    case "create-enum": {
      const literals = change.enum.values.map((value) => `'${value}'`).join(", ");
      return `-- CreateEnum\nCREATE TYPE "${change.enum.name}" AS ENUM (${literals});`;
    }

    case "drop-enum":
      return `-- DESTRUCTIVE: drops enum type "${change.enum}".\nDROP TYPE "${change.enum}";`;

    case "add-feature-sql":
      return change.sql.trim();

    case "drop-feature-sql":
      return (
        "-- NOTE: feature-owned SQL was removed from the specification. It cannot be\n" +
        "-- reversed automatically; review and drop it by hand if it is no longer wanted:\n" +
        commentBlock("  ", change.sql.trim())
      );

    case "add-enum-value":
      return (
        `ALTER TYPE "${change.enum}" ADD VALUE '${change.value}'` +
        `${change.after === null ? "" : ` AFTER '${change.after}'`};`
      );
  }
}

/**
 * Renders an ordered change list to a PostgreSQL migration. `ALTER TYPE ... ADD
 * VALUE` statements are collected into a trailing section because, on
 * PostgreSQL versions before 12, they cannot run in the same transaction block
 * as the other DDL (Prisma wraps a migration in one transaction).
 */
export function renderDiffMigration(
  changes: readonly SchemaChange[],
  _options: { allowDestructive: boolean },
): string {
  const main: string[] = [];
  const enumValues: string[] = [];

  for (const change of changes) {
    if (change.kind === "add-enum-value") {
      enumValues.push(statementFor(change));
    } else {
      main.push(statementFor(change));
    }
  }

  const sections: string[] = [HEADER, ...main];

  if (enumValues.length > 0) {
    sections.push(
      [
        "-- ALTER TYPE ... ADD VALUE cannot run inside a transaction block with other",
        "-- DDL on PostgreSQL < 12. These statements are emitted last for that reason.",
        ...enumValues,
      ].join("\n"),
    );
  }

  return `${sections.join("\n\n")}\n`;
}
