import type { BackendIR, NormalizedEntity, NormalizedField } from "@backend-compiler/compiler";
import { enumFields, foreignKeys, names } from "./naming.js";

const SCALAR_TO_SQL: Readonly<Record<string, string>> = {
  string: "TEXT",
  text: "TEXT",
  integer: "INTEGER",
  decimal: "DECIMAL(65,30)",
  boolean: "BOOLEAN",
  datetime: "TIMESTAMP(3)",
  date: "DATE",
  uuid: "TEXT",
};

function sqlType(entity: NormalizedEntity, field: NormalizedField): string {
  if (field.enumValues) {
    return `"${names.enumType(entity.name, field.name)}"`;
  }
  return SCALAR_TO_SQL[field.type] ?? "TEXT";
}

function sqlDefault(field: NormalizedField): string {
  const value = field.defaultValue;
  if (value === null) return "";
  if (typeof value === "string") return ` DEFAULT '${value.replace(/'/g, "''")}'`;
  return ` DEFAULT ${String(value)}`;
}

function columnLines(entity: NormalizedEntity): string[] {
  const columns: string[] = [
    '    "id" TEXT NOT NULL',
    '    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP',
    '    "updatedAt" TIMESTAMP(3) NOT NULL',
  ];

  if (entity.softDelete) {
    columns.push('    "deletedAt" TIMESTAMP(3)');
  }

  for (const field of entity.fields) {
    const nullability = field.required ? " NOT NULL" : "";
    columns.push(
      `    "${field.name}" ${sqlType(entity, field)}${nullability}${sqlDefault(field)}`,
    );
  }

  for (const key of foreignKeys(entity)) {
    columns.push(`    "${key.name}" TEXT${key.required ? " NOT NULL" : ""}`);
  }

  columns.push(`    CONSTRAINT "${entity.name}_pkey" PRIMARY KEY ("id")`);
  return columns;
}

function createTable(entity: NormalizedEntity): string {
  return [
    "-- CreateTable",
    `CREATE TABLE "${entity.name}" (`,
    columnLines(entity).join(",\n"),
    ");",
  ].join("\n");
}

function createIndexes(entity: NormalizedEntity): string[] {
  const statements: string[] = [];

  for (const field of entity.fields) {
    if (field.unique) {
      statements.push(
        `CREATE UNIQUE INDEX "${entity.name}_${field.name}_key" ON "${entity.name}"("${field.name}");`,
      );
    }
  }

  for (const key of foreignKeys(entity)) {
    if (key.unique) {
      statements.push(
        `CREATE UNIQUE INDEX "${entity.name}_${key.name}_key" ON "${entity.name}"("${key.name}");`,
      );
    }
  }

  for (const index of entity.indexes) {
    const columns = index.fields.map((field) => `"${field}"`).join(", ");
    const suffix = index.unique ? "key" : "idx";
    const name = `${entity.name}_${index.fields.join("_")}_${suffix}`;
    statements.push(
      `CREATE${index.unique ? " UNIQUE" : ""} INDEX "${name}" ON "${entity.name}"(${columns});`,
    );
  }

  if (entity.softDelete) {
    statements.push(
      `CREATE INDEX "${entity.name}_deletedAt_idx" ON "${entity.name}"("deletedAt");`,
    );
  }

  return statements;
}

function foreignKeyStatements(entity: NormalizedEntity): string[] {
  return entity.relations
    .filter((relation) => relation.owner && relation.foreignKey !== null)
    .map((relation) => {
      const onDelete = relation.required ? "CASCADE" : "SET NULL";
      return (
        `ALTER TABLE "${entity.name}" ADD CONSTRAINT "${entity.name}_${relation.foreignKey}_fkey" ` +
        `FOREIGN KEY ("${relation.foreignKey}") REFERENCES "${relation.target}"("id") ` +
        `ON DELETE ${onDelete} ON UPDATE CASCADE;`
      );
    });
}

function createEnums(ir: BackendIR): string[] {
  return ir.entities.flatMap((entity) =>
    enumFields(entity).map(({ typeName, values }) => {
      const literals = values.map((value) => `'${value}'`).join(", ");
      return `CREATE TYPE "${typeName}" AS ENUM (${literals});`;
    }),
  );
}

/**
 * Emits the initial migration as SQL rather than shelling out to
 * `prisma migrate dev`, which needs a live shadow database. The result is
 * deterministic and applies offline with `prisma migrate deploy`.
 *
 * `extraSql` carries statements features cannot express through the Prisma
 * schema — most importantly the reservation overlap `EXCLUDE` constraint.
 */
export function renderInitialMigration(ir: BackendIR, extraSql: readonly string[]): string {
  const sections: string[] = [
    "-- Generated by backendgen. Applied with `prisma migrate deploy`.",
  ];

  const enums = createEnums(ir);
  if (enums.length > 0) {
    sections.push(["-- CreateEnum", ...enums].join("\n"));
  }

  for (const entity of ir.entities) {
    sections.push(createTable(entity));
  }

  const indexes = ir.entities.flatMap(createIndexes);
  if (indexes.length > 0) {
    sections.push(["-- CreateIndex", ...indexes].join("\n"));
  }

  const constraints = ir.entities.flatMap(foreignKeyStatements);
  if (constraints.length > 0) {
    sections.push(["-- AddForeignKey", ...constraints].join("\n"));
  }

  for (const statement of extraSql) {
    sections.push(statement.trim());
  }

  return `${sections.join("\n\n")}\n`;
}

export const MIGRATION_DIRECTORY = "prisma/migrations/00000000000000_init";
